node {

   

        stage('Checkout') {
            git url: 'https://github.com/gauthamdharsan/test.git', credentialsId: 'git', branch: 'master'
        }

        stage('Build') {
            sh 'mvn clean install'

            def pom = readMavenPom file:'pom.xml'
            print pom.version
            env.version = pom.version
        }

        stage('Image') {
            dir ('discovery-service') {



                def app = docker.build "gauthamdharsan/discovery-service:${env.version}"
                app.push()
            }
        }

        stage ('Run') {
             docker.image("gauthamdharsan/discovery-service:${env.version}").run('-p 8761:8761 -h discovery --name discovery')
        }
        

        stage ('Final') {
            build job: 'account-service-pipeline', wait: false
        }      

    }

