
node {

    withMaven(maven:'maven') {

        stage('Checkout') {
            git url: 'https://github.com/leo-coutinho/Sample-Spring-Microservices.git', credentialsId: 'leo-coutinho', branch: 'master'
        }

        stage('Build') {
            sh 'mvn clean install'

            def pom = readMavenPom file:'pom.xml'
            print pom.version
            env.version = pom.version
        }

        stage('Image') {
            dir ('account-service') {
                def app = docker.build "localhost:5000/account-service:${env.version}"
                app.push()
            }
        }

        stage ('Run') {
             docker.image("localhost:5000/account-service:${env.version}").run('-p 8888:8888 -h accounts --name accounts --link discovery')
        }

        stage ('Final') {
            build job: 'customer-service-pipeline', wait: false
        }      

    }

}