node {

   

        stage('Checkout') {
            git url: 'https://github.com/gauthamdharsan/test.git', credentialsId: 'git', branch: 'master'
        }

        stage('Build') {
            sh 'mvn clean install'

            def pom = readMavenPom file:'pom.xml'
            print pom.version
            env.version = pom.version
        }

        stage('Image') {
            dir ('customer-service') {
                def app = docker.build "gauthamdharsan/customer-service:${env.version}"
                app.push()
            }
        }

        stage ('Run') {
            docker.image("gauthamdharsan/customer-service:${env.version}").run('-p 3333:3333 -h customer --name customer --link discovery --link accounts')
        }

        stage ('Final') {
            build job: 'gateway-service-pipeline', wait: false
        }      

    }

